"""Chat and messaging ORM models."""
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, Float
from backend.config.database import Base


class AIChatMessages(Base):
    """AI chat messages model."""
    __tablename__ = 'ai_chat_messages'

    id = Column(Integer, primary_key=True, autoincrement=True)
    conversation_id = Column(String(50), doc="Conversation ID")
    agent_id = Column(Integer, default=None, doc="Agent ID (for multi-agent support)")
    flag = Column(Integer, doc="0=send, 1=receive")
    title = Column(Text, default=None, doc="Title")
    content = Column(Text, doc="Message content")
    attachment_list = Column(Text, doc="Attachment list")
    document_content = Column(Text, doc="Document content")
    image_json = Column(Text, doc="Image JSON")
    km_list = Column(Text, doc="Knowledge base list")
    km_content = Column(Text, doc="Knowledge base content")
    owner_name = Column(String(100), doc="Owner name")
    owner_account = Column(String(100), doc="Owner account")
    friend_name = Column(String(100), doc="Friend name")
    friend_account = Column(String(100), doc="Friend account")
    create_time = Column(DateTime, default=datetime.now, doc="Create time")
    is_delete = Column(Boolean, default=False, doc="Soft delete")
    is_first = Column(Boolean, default=False, doc="Is first message")
    stick_time = Column(DateTime, nullable=True, doc="Stick time")
    label = Column(String(50), doc="Category label")


class AIFriend(Base):
    """AI friend model."""
    __tablename__ = 'ai_friend'

    id = Column(Integer, primary_key=True, autoincrement=True)
    account = Column(String(100), doc="Account")
    nick_name = Column(String(200), doc="Nickname")
    groups = Column(Text, doc="Groups")
    owner_sns_account = Column(String(100), doc="Owner SNS account")
    memo = Column(Text, doc="Memo")
    sign = Column(String(200), doc="Signature")
    subscription = Column(String(100), doc="Subscription status")
    name = Column(String(200), doc="Real name")
    borndate = Column(String(100), doc="Birth date")
    gender = Column(Integer, doc="Gender")
    area = Column(String(100), doc="Area")
    city = Column(String(100), doc="City")
    address = Column(String(200), doc="Address")
    mail = Column(String(100), doc="Email")
    phone = Column(String(100), doc="Phone")
    organization = Column(String(200), doc="Organization")
    title = Column(String(100), doc="Title")
    position = Column(String(100), doc="Position")
    new_message_flag = Column(Boolean, default=False, doc="Has new message")
    last_message_time = Column(DateTime, doc="Last message time")
    is_delete = Column(Boolean, default=False, doc="Soft delete")
    create_time = Column(DateTime, default=datetime.now, doc="Create time")


class AIChatInform(Base):
    """AI chat notification model."""
    __tablename__ = 'ai_chat_inform'

    id = Column(Integer, primary_key=True, autoincrement=True)
    inform_id = Column(String(50), doc="Notification ID")
    title = Column(Text, default=None, doc="Title")
    content = Column(Text, doc="Content")
    type = Column(String(100), doc="Type")
    status = Column(String(100), doc="Status")
    owner_name = Column(String(100), doc="Owner name")
    owner_account = Column(String(100), doc="Owner account")
    friend_name = Column(String(100), doc="Friend name")
    friend_account = Column(String(100), doc="Friend account")
    create_time = Column(DateTime, default=datetime.now, doc="Create time")
    is_delete = Column(Boolean, default=False, doc="Soft delete")


class AiChatCfg(Base):
    """AI chat configuration model."""
    __tablename__ = 'aichat_cfg'

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(100), doc="User ID")
    account = Column(String(100), doc="Account")
    password = Column(String(256), doc="Password hash")
    nickname = Column(String(100), doc="Nickname")
    sign = Column(String(200), doc="Signature")
    status = Column(String(100), doc="Online status")
    humantakeover = Column(Integer, default=0, doc="Human takeover")
    name = Column(String(200), doc="Name")
    borndate = Column(DateTime, default=datetime.now, doc="Birth date")
    gender = Column(Integer, doc="Gender")
    area = Column(String(100), doc="Area")
    state = Column(String(100), doc="State")
    city = Column(String(100), doc="City")
    community = Column(String(100), doc="Community")
    street_block = Column(String(100), doc="Street block")
    address = Column(String(200), doc="Address")
    mail = Column(String(100), doc="Email")
    imaccount = Column(String(100), doc="IM account")
    phone = Column(String(100), doc="Phone")
    organization = Column(String(200), doc="Organization")
    title = Column(String(100), doc="Title")
    orgposition = Column(String(100), doc="Position")
    memo = Column(String(200), doc="Memo")
    islimittotalmessage = Column(Boolean, default=True, doc="Limit total messages")
    islimitmessagepp = Column(Boolean, default=True, doc="Limit messages per person")
    totalmessages = Column(Integer, doc="Total messages")
    ppmessages = Column(Integer, doc="Messages per person")
    serveraddress = Column(String(100), doc="Server address")
    port = Column(Integer, doc="Port")
    ssl = Column(Boolean, doc="SSL")
    resource = Column(String(100), doc="Resource")
    proxyused = Column(Boolean, doc="Proxy used")
    proxyaddress = Column(String(100), doc="Proxy address")
    proxyport = Column(Integer, doc="Proxy port")
    proxyssl = Column(Boolean, doc="Proxy SSL")
    savepasswordlocal = Column(Boolean, default=True, doc="Save password locally")
    autoconnect = Column(Boolean, default=True, doc="Auto connect")
    sendreceipt = Column(Boolean, default=True, doc="Send receipt")
    sendreadflag = Column(Boolean, default=True, doc="Send read flag")
    sendchatstatus = Column(Boolean, default=True, doc="Send chat status")
    sendgroupchatstatus = Column(Boolean, default=True, doc="Send group chat status")
    agreeallfriendrequest = Column(Boolean, default=True, doc="Agree all friend requests")
    position = Column(Integer, default=9999, doc="Display position")
    is_show = Column(Boolean, default=True, doc="Is visible")
    is_delete = Column(Boolean, default=False, doc="Soft delete")
    create_time = Column(DateTime, default=datetime.now, doc="Create time")

    # Map-related fields
    nationid = Column(String(100), doc="Nation ID")
    nationpassword = Column(String(100), doc="Nation password")
    sns_url = Column(Text, doc="SNS URL")
    avatar = Column(Text, doc="Avatar")
    avatar3d = Column(Text, doc="3D Avatar")
    house3d = Column(Text, doc="3D House")
    map_type = Column(String(100), doc="Map type")
    map_api_key = Column(Text, doc="Map API key")
    map_id = Column(Text, doc="Map ID")
    current_position = Column(String(100), doc="Current position")
    current_place = Column(String(500), doc="Current place")
    last_position = Column(String(100), doc="Last position")
    home_position = Column(String(100), doc="Home position")
    positionx = Column(Float, doc="X coordinate")
    positiony = Column(Float, doc="Y coordinate")
    positionz = Column(Float, doc="Z coordinate")
    route_start = Column(String(500), doc="Route start")
    route_end = Column(String(500), doc="Route end")
    route_status = Column(String(100), doc="Route status")
    route_current_position = Column(String(100), doc="Route current position")
    route = Column(Text, doc="Route")
    level = Column(Integer, doc="Level")
    credit = Column(Integer, doc="Credit")
    money = Column(Float, doc="Money")
    token_unit = Column(String(100), doc="Token unit")
    life_point = Column(Integer, doc="Life point")
    energy_point = Column(Integer, doc="Energy point")
    move_point = Column(Integer, doc="Move point")
    exp_point = Column(Integer, doc="Experience point")
    iq_point = Column(Integer, doc="IQ point")
    profession = Column(String(200), doc="Profession")
    handle_after_trade = Column(String(200), doc="Handle after trade")
    handle_content = Column(Text, doc="Handle content")
    event_before_decistion = Column(String(200), doc="Event before decision")
    event_after_decistion = Column(String(200), doc="Event after decision")
    event_receive_msg = Column(String(200), doc="Event receive message")
    event_before_send_msg = Column(String(200), doc="Event before send message")
    event_before_move = Column(String(200), doc="Event before move")
    event_after_move = Column(String(200), doc="Event after move")
    event_before_use_tool = Column(String(200), doc="Event before use tool")
    event_after_use_tool = Column(String(200), doc="Event after use tool")


class HumanChatCfg(Base):
    """Human chat configuration model."""
    __tablename__ = 'humanchat_cfg'

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String(100), doc="User ID")
    account = Column(String(100), doc="Account")
    password = Column(String(256), doc="Password hash")
    nickname = Column(String(100), doc="Nickname")
    sign = Column(String(200), doc="Signature")
    status = Column(String(100), doc="Online status")
    name = Column(String(200), doc="Name")
    borndate = Column(DateTime, default=datetime.now, doc="Birth date")
    gender = Column(Integer, doc="Gender")
    area = Column(String(100), doc="Area")
    city = Column(String(100), doc="City")
    address = Column(String(200), doc="Address")
    mail = Column(String(100), doc="Email")
    imaccount = Column(String(100), doc="IM account")
    phone = Column(String(100), doc="Phone")
    organization = Column(String(200), doc="Organization")
    title = Column(String(100), doc="Title")
    orgposition = Column(String(100), doc="Position")
    memo = Column(String(200), doc="Memo")
    serveraddress = Column(String(100), doc="Server address")
    port = Column(Integer, doc="Port")
    ssl = Column(Boolean, doc="SSL")
    resource = Column(String(100), doc="Resource")
    proxyused = Column(Boolean, doc="Proxy used")
    proxyaddress = Column(String(100), doc="Proxy address")
    proxyport = Column(Integer, doc="Proxy port")
    proxyssl = Column(Boolean, doc="Proxy SSL")
    savepasswordlocal = Column(Boolean, default=True, doc="Save password locally")
    autoconnect = Column(Boolean, default=True, doc="Auto connect")
    sendreceipt = Column(Boolean, default=True, doc="Send receipt")
    sendreadflag = Column(Boolean, default=True, doc="Send read flag")
    sendchatstatus = Column(Boolean, default=True, doc="Send chat status")
    sendgroupchatstatus = Column(Boolean, default=True, doc="Send group chat status")
    autoaway = Column(Boolean, default=True, doc="Auto away")
    autona = Column(Boolean, default=True, doc="Auto N/A")
    agreeallfriendrequest = Column(Boolean, default=True, doc="Agree all friend requests")
    is_delete = Column(Boolean, default=False, doc="Soft delete")
    create_time = Column(DateTime, default=datetime.now, doc="Create time")
