# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TaskPageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import time
import urllib
import webbrowser, re

from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebEngineWidgets import QWebEnginePage, QWebEngineFullScreenRequest, QWebEngineView, QWebEngineProfile
from PyQt5.QtWidgets import QLabel, QCheckBox, QComboBox, QSplitter, QFrame

from qtpy.QtCore import Qt, QMetaObject, Signal, Slot, QEvent
from pathlib import Path

sys.path.append("../..")
sys.path.append("../../..")

from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QWidget, QApplication, QMessageBox, QMainWindow, QPushButton, QVBoxLayout, QTabWidget
from PyQt5.QtCore import pyqtSlot, Qt, QUrl, QFileInfo, pyqtProperty
from prompts import PromptDialog, PromptManager
from db.DBFactory import Session, Prompt

import sys
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QLineEdit, QPushButton, QVBoxLayout, QWidget, QMenu, QAction, QHBoxLayout, QShortcut
)
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl, Qt
from PyQt5.QtGui import QKeySequence

class MessageHandler(QWidget):
    on_message = pyqtSignal(str)
    on_message_checked = pyqtSignal(int, str)

    def __init__(self):
        super().__init__()
        self.theinnervalue = "cjrok"

    def PyQt52WebValue(self):
        return self.theinnervalue

    @pyqtSlot(str, result=str)
    def Web2PyQt5Value(self, tmpstr):
        self.theinnervalue = self.theinnervalue + tmpstr
        QMessageBox.information(self, "从网页来的信息", tmpstr)

    @pyqtSlot(int, str, result=str)
    def check_message(self, i, status):
        print("i:", i)
        print("status", status)
        self.on_message_checked.emit(i, status)

    def pass_message(self, message):
        self.on_message.emit(message)

    thevalue = pyqtProperty(str, fget=PyQt52WebValue, fset=Web2PyQt5Value)


class Ui_TaskPageWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(800, 600)
        TaskWidget.setContentsMargins(0, 0, 0, 0)
        icon = QtGui.QIcon()
        icon.addFile("images/mail.png")
        TaskWidget.setWindowIcon(icon)

        self.vboxlayout = QtWidgets.QVBoxLayout(TaskWidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)

        self.hboxlayoutlabel = QtWidgets.QHBoxLayout()
        spacerItem_label_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayoutlabel.addItem(spacerItem_label_left)

        self.title_label = QLabel("Agent对象：", TaskWidget)  # 修改了这里的title_label
        self.title_label.setStyleSheet("color: #146ebe;font-weight:bold")
        self.title_label.setFixedHeight(30)
        self.title_label.setContentsMargins(0, 0, 0, 0)
        self.hboxlayoutlabel.addWidget(self.title_label)

        spacerItem_label_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayoutlabel.addItem(spacerItem_label_right)

        self.vboxlayout.addLayout(self.hboxlayoutlabel)

        self.splitter = QSplitter(Qt.Horizontal, TaskWidget)
        self.messageBrowser = QWebEngineView()
        self.messageBrowser.setObjectName("messageBrowser")

        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setStyleSheet("QFrame { border: 1px solid #c0c0c0;}")
        self.frame_layout = QtWidgets.QVBoxLayout(self.frame)
        self.frame_layout.addWidget(self.messageBrowser)

        self.tabWidget = QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.South)

        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.tabLayout_output = QtWidgets.QVBoxLayout(self.tab_output)
        self.tabLayout_output.setContentsMargins(0, 0, 0, 0)
        self.output_webview = QWebEngineView(self.tab_output)
        self.tabLayout_output.addWidget(self.output_webview)
        self.tabWidget.addTab(self.tab_output, "输出")

        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.tabLayout_log = QVBoxLayout(self.tab_log)
        self.tabLayout_log.setContentsMargins(0, 0, 0, 0)
        self.textEdit_log = QtWidgets.QTextEdit(self.tab_log)
        self.textEdit_log.setReadOnly(True)
        self.tabLayout_log.addWidget(self.textEdit_log)
        self.tabWidget.addTab(self.tab_log, "日志")

        self.splitter.setSizes([1, ])
        self.vboxlayout.addWidget(self.splitter)

        self.hboxlayout = QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)

        self.attach_button = QPushButton(TaskWidget)
        icon1 = QtGui.QIcon()
        icon1.addFile("images/attachment.png")
        self.attach_button.setIcon(icon1)
        self.attach_button.setObjectName("attachButton")
        self.attach_button.clicked.connect(self.add_attachment_area)
        self.hboxlayout.addWidget(self.attach_button)

        self.kmButton = QPushButton(TaskWidget)
        self.kmButton.setIcon(QtGui.QIcon("images/km.png"))
        self.kmButton.setObjectName("kmButton")
        self.hboxlayout.addWidget(self.kmButton)

        self.llm_button = QPushButton(TaskWidget)
        icon2 = QtGui.QIcon()
        icon2.addFile("images/plugin.png")
        self.llm_button.setIcon(icon2)
        self.llm_button.setObjectName("llmButton")
        self.hboxlayout.addWidget(self.llm_button)

        self.model_select_checkbox = QCheckBox("指定模型", TaskWidget)
        self.hboxlayout.addWidget(self.model_select_checkbox)

        self.task_mode_checkbox = QCheckBox("任务模式", TaskWidget)
        self.hboxlayout.addWidget(self.task_mode_checkbox)

        self.history_mode_checkbox = QCheckBox("指定上下文", TaskWidget)
        self.hboxlayout.addWidget(self.history_mode_checkbox)

        self.prompt_combobox = QComboBox(TaskWidget)
        self.prompt_combobox.addItem("请选择提示词")
        self.prompt_combobox.addItem("a.你是个资深的程序员")
        self.prompt_combobox.addItem("b.你是个资深的架构师")
        self.hboxlayout.addWidget(self.prompt_combobox)

        self.manage_button = QPushButton("管理", TaskWidget)
        self.hboxlayout.addWidget(self.manage_button)

        self.output_checkbox = QCheckBox("输出", TaskWidget)
        self.output_checkbox.stateChanged.connect(self.toggle_output_checkbox)
        self.output_checkbox.setChecked(False)
        self.hboxlayout.addWidget(self.output_checkbox)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.hboxlayout1 = QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.messageEdit = QtWidgets.QTextEdit(TaskWidget)
        self.messageEdit.setFixedHeight(45)
        self.messageEdit.setStyleSheet("""
            QTextEdit {
                border-radius: 2px;
                border: 1px solid #c0c0c0;
            }
            QTextEdit:focus {
                border-color: #61addf;
            }
        """)
        self.messageEdit.setObjectName("messageEdit")
        self.messageEdit.textChanged.connect(self.adjustHeight)
        self.hboxlayout1.addWidget(self.messageEdit)

        self.sendButton = QPushButton(TaskWidget)
        icon3 = QtGui.QIcon()
        icon3.addFile("images/sendmessage.png")
        self.sendButton.setIcon(icon3)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout1.addWidget(self.sendButton)
        self.vboxlayout.addLayout(self.hboxlayout1)

        self.retranslateUi(TaskWidget)
        QtCore.QMetaObject.connectSlotsByName(TaskWidget)
        self.remaining_attachments = 0  # 初始化可见附件计数

    def adjustHeight(self):
        line_height = 20
        min_height = 40
        max_height = 200
        document = self.messageEdit.document()
        document_height = document.size().height()
        lines = int(document_height / line_height)
        new_height = max(min_height, min(max_height, lines * line_height))
        self.messageEdit.setFixedHeight(new_height + 5)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Message"))
        self.attach_button.setText(_translate("TaskWidget", "附件"))
        self.kmButton.setText(_translate("TaskWidget", "知识库"))
        self.llm_button.setText(_translate("TaskWidget", "模型"))
        self.sendButton.setText(_translate("TaskWidget", "发送"))
        self.sendButton.setShortcut(QtGui.QKeySequence(Qt.ControlModifier + Qt.Key_Return))

    def toggle_output_checkbox(self, state):
        if state == Qt.Checked:
            self.splitter.setSizes([300, 1])
        else:
            self.splitter.setSizes([1, ])

    def add_attachment_area(self):
        attachments = ["附件1: example1.txt", "附件2: example2.txt"]
        self.remaining_attachments = len(attachments)  # 设置剩余附件数量

        if not hasattr(self, 'attachment_frame'):
            self.attachment_frame = QFrame()
            self.attachment_frame.setObjectName("attachmentFrame")
            self.attachment_layout = QHBoxLayout(self.attachment_frame)
            self.attachment_layout.setObjectName("attachmentLayout")
            self.attachment_layout.setContentsMargins(0, 0, 0, 0)
            self.attachment_layout.setAlignment(Qt.AlignCenter)  # 居中显示
            self.attachment_frame.setMaximumHeight(40)  # 限制高度为40
            self.vboxlayout.insertWidget(3, self.attachment_frame)

        self.attachment_frame.setVisible(True)

        for attachment in attachments:
            attachment_label = QLabel(attachment)

            # Create a clickable label instead of a checkbox
            delete_label = QLabel('<a href="#">删除</a>')
            delete_label.setOpenExternalLinks(False)
            delete_label.linkActivated.connect(lambda _, lbl=attachment_label, del_lbl=delete_label: self.remove_attachment(lbl, del_lbl))

            self.attachment_layout.addWidget(attachment_label)
            self.attachment_layout.addWidget(delete_label)

            self.attachment_layout.setAlignment(QtCore.Qt.AlignCenter)

    def remove_attachment(self, attachment_label, delete_label):
        attachment_label.setVisible(False)
        delete_label.setVisible(False)
        self.remaining_attachments -= 1  # 减少剩余附件计数
        self.check_attachments_visibility()

    def check_attachments_visibility(self):
        if self.remaining_attachments == 0:
            self.attachment_frame.setVisible(False)

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    TaskWidget = QtWidgets.QWidget()
    ui = Ui_TaskPageWidget()
    ui.setupUi(TaskWidget)
    TaskWidget.show()
    sys.exit(app.exec_())
