# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TaskPageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import time
import urllib

from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebEngineWidgets import QWebEnginePage, QWebEngineFullScreenRequest, QWebEngineView, QWebEngineProfile
from PyQt5.QtWidgets import QLabel, QCheckBox, QComboBox

from qtpy.QtCore import Qt, QMetaObject, Signal, Slot, QEvent
from pathlib import Path



sys.path.append("../..")
sys.path.append("../../..")

from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QWidget, QApplication, QMessageBox, QMainWindow, QPushButton, QVBoxLayout
from PyQt5.QtCore import pyqtSlot, Qt, QUrl, QFileInfo, pyqtProperty
from prompts import PromptDialog,PromptManager
from db.DBFactory import Session, Prompt

import sys
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QLineEdit, QPushButton, QVBoxLayout, QWidget, QMenu, QAction, QHBoxLayout, QShortcut
)
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl, Qt
from PyQt5.QtGui import QKeySequence

class MessageHandler(QWidget):
    on_message = pyqtSignal(str)

    def __init__(self):
        super().__init__()
        self.theinnervalue = "cjrok"

    def PyQt52WebValue(self):
        return self.theinnervalue

    @pyqtSlot(str, result=str)
    def Web2PyQt5Value(self, tmpstr):
        self.theinnervalue = self.theinnervalue + tmpstr
        QMessageBox.information(self, "从网页来的信息", tmpstr)

    def pass_message(self, messsage):
        self.on_message.emit(messsage)

    thevalue = pyqtProperty(str, fget=PyQt52WebValue, fset=Web2PyQt5Value)


class Ui_TaskPageWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(400, 300)
        TaskWidget.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        icon = QtGui.QIcon()
        icon.addFile("images/mail.png")
        TaskWidget.setWindowIcon(icon)
        self.vboxlayout = QtWidgets.QVBoxLayout(TaskWidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)  # 不留间隙

        # 添加标签到布局中
        self.hboxlayoutlabel = QtWidgets.QHBoxLayout()

        spacerItem_label_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayoutlabel.addItem(spacerItem_label_left)  # 通过留空来居中

        if self.task_type == 'single':
            self.title_label = QLabel("Agent对象：" + self.name, TaskWidget)
        else:
            self.title_label = QLabel("Agent群：" + self.name, TaskWidget)
        self.title_label.setStyleSheet("color: #146ebe;font-weight:bold")
        self.title_label.setFixedHeight(30)  # 影响间隙
        self.title_label.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        self.hboxlayoutlabel.addWidget(self.title_label)

        spacerItem_label_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayoutlabel.addItem(spacerItem_label_right)  # 通过留空来居中

        self.vboxlayout.addLayout(self.hboxlayoutlabel)

        # self.messageBrowser = QtWidgets.QTextBrowser(TaskWidget)
        self.messageBrowser = QWebEngineView()
        # self.messageBrowser = QWebEngineView()
        self.messageBrowser.setObjectName("messageBrowser")
        # self.messageBrowser.setAttribute(Qt.WA_StyledBackground,True)
        # self.messageBrowser.setStyleSheet("""
        #        QWebEngineView {
        #            background-color: red; /* 设置背景色为红色 */
        #        }
        #    """)
        # self.messageBrowser.setStyleSheet("{border: 2px solid red;display:none}")
        # self.messageBrowser.setVisible(False)

        self.frame = QtWidgets.QFrame(self)
        self.frame.setStyleSheet("QFrame { border: 1px solid #c0c0c0;}")
        self.frame_layout = QtWidgets.QVBoxLayout(self.frame)
        self.frame_layout.addWidget(self.messageBrowser)
        # self.frame_layout.addWidget(self.messageBrowser)

        self.vboxlayout.addWidget(self.frame)

        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.attach_button = QtWidgets.QPushButton(TaskWidget)
        icon1 = QtGui.QIcon()
        icon1.addFile("images/attachment.png")
        self.attach_button.setIcon(icon1)
        self.attach_button.setObjectName("fontButton")
        self.hboxlayout.addWidget(self.attach_button)



        self.kmButton = QtWidgets.QPushButton(TaskWidget)
        self.kmButton.setIcon(QtGui.QIcon("images/km.png"))
        self.kmButton.setObjectName("kmButton")
        self.hboxlayout.addWidget(self.kmButton)

        self.llm_button = QtWidgets.QPushButton(TaskWidget)
        icon2 = QtGui.QIcon()
        icon2.addFile("images/plugin.png")
        self.llm_button.setIcon(icon2)
        self.llm_button.setObjectName("videoButton")
        self.hboxlayout.addWidget(self.llm_button)


        self.model_select_checkbox = QCheckBox("指定模型", TaskWidget)
        self.hboxlayout.addWidget(self.model_select_checkbox)

        self.task_mode_checkbox = QCheckBox("任务模式", TaskWidget)
        self.hboxlayout.addWidget(self.task_mode_checkbox)

        self.history_mode_checkbox = QCheckBox("指定历史", TaskWidget)
        self.hboxlayout.addWidget(self.history_mode_checkbox)

        self.prompt_combobox = QComboBox(TaskWidget)
        self.prompt_combobox.addItem("请选择提示词")
        self.prompt_combobox.addItem("a.你是个资深的程序员")
        self.prompt_combobox.addItem("b.你是个资深的架构师")
        self.hboxlayout.addWidget(self.prompt_combobox)

        self.manage_button = QtWidgets.QPushButton("管理", TaskWidget)
        self.hboxlayout.addWidget(self.manage_button)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.messageEdit = QtWidgets.QTextEdit(TaskWidget)
        self.messageEdit.setFixedHeight(45)  # 假设每行高度为20像素
        self.messageEdit.setStyleSheet("""
            QTextEdit {
                border-radius: 2px; /* 设置圆角 */
                border: 1px solid #c0c0c0; /* 设置边框 */
            }
            QTextEdit:focus {
                border-color: #61addf; /* 设置焦点时的边框颜色 */
            }
        """)

        # self.messageEdit.returnPressed.connect(self.clear_content)
        self.messageEdit.setObjectName("messageEdit")
        self.hboxlayout1.addWidget(self.messageEdit)
        self.sendButton = QtWidgets.QPushButton(TaskWidget)
        icon3 = QtGui.QIcon()
        icon3.addFile("images/sendmessage.png")
        self.sendButton.setIcon(icon3)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout1.addWidget(self.sendButton)
        self.vboxlayout.addLayout(self.hboxlayout1)

        self.retranslateUi(TaskWidget)

        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Message"))
        print("go setting")
        #         self.messageBrowser.setHtml(_translate("TaskWidget", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        # "p, li { white-space: pre-wrap; }\n"
        # "</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:14pt; font-weight:400; font-style:normal;background-color: #f0f0f0;border:\'solid 1px red;\' \">"
        # "</body></html>"))

        # self.messageBrowser.setHtml(QtCore.QCoreApplication.translate("TaskWidget", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        #                                                                                "p, li { white-space: pre-wrap; }\n"
        #                                                                                "</style><script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/1.4.4/jquery.min.js' type='text/javascript'></script><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/default.min.css'><script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js'></script></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:14pt; font-weight:400; font-style:normal;background-color: #f0f0f0;border:\'solid 1px red;\' \">"
        #                                                                                "<script>hljs.highlightAll();</script></body></html>"))

        file_path = os.path.join(Path(__file__).resolve().parent.parent, "scripts", "taskpagemsgbox.html")
        # file_path = os.path.join(Path(__file__).resolve().parent.parent, "scripts", "index3.html")
        print(file_path)
        url_string = QUrl.fromLocalFile(file_path)
        # url_string = urllib.request.pathname2url(os.path.join(Path(__file__).resolve().parent.parent, "scripts", "taskpagemsgbox.html"))
        print("transform")
        print(url_string)
        # self.messageBrowser.page().load(url_string)
        self.messageBrowser.page().load(url_string)
        global channel
        global message_handler
        channel = QWebChannel()
        message_handler = MessageHandler()
        self.message_handler = message_handler
        self.channel = channel
        channel.registerObject("message_handler", message_handler)

        # self.messageBrowser.page().setWebChannel(channel)
        self.messageBrowser.page().setWebChannel(channel)

        # file_path = os.path.join(Path(__file__).resolve().parent, "scripts", "taskpagemsgbox.html")
        # url_string = QUrl.fromLocalFile(file_path)
        # web_browser.page().load(url_string)

        # self.messageBrowser.page().load(url_string)

        # self.messageBrowser.setHtml(QtCore.QCoreApplication.translate("TaskWidget",thehtml))

        # self.shared=shared

        self.attach_button.setText(_translate("TaskWidget", "附件"))
        self.kmButton.setText(_translate("TaskWidget", "知识库"))
        self.llm_button.setText(_translate("TaskWidget", "模型"))
        self.sendButton.setText(_translate("TaskWidget", "发送"))
        # self.sendButton.setShortcut(_translate("TaskWidget", "Return"))
        self.sendButton.setShortcut(QtGui.QKeySequence(Qt.ControlModifier + Qt.Key_Return))


        #search 相关
        self.messageBrowser.setContextMenuPolicy(Qt.CustomContextMenu)
        self.messageBrowser.customContextMenuRequested.connect(self.show_context_menu)

        self.search_box = QLineEdit()
        self.search_box.setPlaceholderText("在此输入搜索词")
        self.search_box.setVisible(False)
        self.search_box.returnPressed.connect(self.search_in_page)
        self.search_box.setStyleSheet("""
                            QLineEdit {
                                border: 1px solid #ccc;
                                border-radius: 10px;
                                padding: 2px 8px;
                                background: #fff;
                                selection-background-color: #0078d7;
                            }
                        """)

        self.search_button = QPushButton("×")
        self.search_button.clicked.connect(self.toggle_search_box)
        self.search_button.setVisible(False)
        self.search_button.setStyleSheet("""
                            QPushButton {
                                border: none;
                                background: transparent;
                                font-weight: bold;
                            }
                            QPushButton:hover {
                                color: #ff0000;
                            }
                        """)

        self.shortcut = QShortcut(QKeySequence('Ctrl+F'), self)
        self.shortcut.activated.connect(self.toggle_search_box)

        # 将搜索框放置在 QWebEngineView 的右上角
        self.search_container = QWidget(self.messageBrowser)
        self.search_container.setFixedSize(250, 30)
        self.search_container.move(self.messageBrowser.width() - 270, 10)  # 定位到右上角
        self.search_container.setVisible(True)

        search_layout = QHBoxLayout()
        search_layout.addWidget(self.search_box)
        search_layout.addWidget(self.search_button)
        search_layout.setContentsMargins(0, 0, 0, 0)  # 去除边距
        self.search_container.setLayout(search_layout)





    def toggle_chat_mode(self, state):

        if state == QtCore.Qt.Checked:
            self.agent.chat_mode = 'task'
        else:
            self.agent.chat_mode = 'chat'

    def toggle_history_mode(self, state):

        if state == QtCore.Qt.Checked:
            self.agent.history_mode = 'specify'
            self.messages = [{"role": "system", "content": f"{self.system_role_prompt}"}]
        else:
            self.agent.history_mode = 'all'

    def set_prompt_string(self, index):
        # if index>0:
        #     self.agent.current_prompt = self.prompt_combobox.itemText(index)
        # else:
        #     self.agent.current_prompt = ""
        title = self.prompt_combobox.currentText()
        content = self.prompt_combobox.currentData()
        print(f"Title: {title}, Content: {content}")
        self.system_role_prompt = content


    def toggle_model_select_type(self, state):
        if state == QtCore.Qt.Checked:
            self.agent.model_select_type = 'specify'
        else:
            self.agent.model_select_type = 'auto'

    def on_manage_button_clicked(self):
        print("hello")
        self.prompt_manager = PromptManager(self)
        self.prompt_manager.exec_()

    def update_prompts_in_combobox(self):
        current_value = self.prompt_combobox.currentText()
        self.prompt_combobox.clear()
        session = Session()
        prompts = session.query(Prompt).all()
        for prompt in prompts:
            self.prompt_combobox.addItem(prompt.title, prompt.content)
        session.close()

        index = self.prompt_combobox.findText(current_value)
        if index != -1:
            self.prompt_combobox.setCurrentIndex(index)

    def print_selected_prompt(self):
        title = self.prompt_combobox.currentText()
        content = self.prompt_combobox.currentData()
        print(f"Title: {title}, Content: {content}")

    #webpage serch

    def show_context_menu(self, position):
        context_menu = QMenu()

        copy_action = QAction("拷贝(Ctrl+C)", self)
        copy_action.triggered.connect(self.copy_text)
        context_menu.addAction(copy_action)

        search_action = QAction("搜索(Ctrl+F1)", self)
        search_action.triggered.connect(self.toggle_search_box)
        context_menu.addAction(search_action)

        # 把“搜索”选项移动到“拷贝”下面
        actions = context_menu.actions()
        actions[0], actions[1] = actions[1], actions[0]

        context_menu.exec_(self.messageBrowser.mapToGlobal(position))

    def copy_text(self):
        self.messageBrowser.triggerPageAction(QWebEnginePage.Copy)

    def toggle_search_box(self):
        print("..taskpage searching..")
        if self.search_box.isVisible():
            self.search_box.setVisible(False)
            self.search_button.setVisible(False)
            self.messageBrowser.findText("")  # 清除搜索状态
            self.search_box.clear()  # 清空搜索框的内容
        else:
            self.search_box.setVisible(True)
            self.search_button.setVisible(True)
            self.search_box.setFocus()

    def search_in_page(self):
        search_text = self.search_box.text()
        self.messageBrowser.findText(search_text)





