# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_TaskPageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os
import sys
import subprocess
import time
import urllib
import pyperclip
import webbrowser,re
from urllib.parse import urlparse
from PyQt5 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets
from PyQt5.QtCore import QUrl
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebEngineWidgets import QWebEnginePage, QWebEngineFullScreenRequest, QWebEngineView, QWebEngineProfile, QWebEngineSettings
from PyQt5.QtWidgets import QLabel, QCheckBox, QComboBox, QSplitter, QFrame, QDialog, QGroupBox
from PyQt5.QtWidgets import (QApplication, QDialog, QVBoxLayout,
                             QFormLayout, QLabel, QComboBox,
                             QLineEdit, QPushButton, QHBoxLayout, QSpacerItem, QSizePolicy)

from qtpy.QtCore import Qt, QMetaObject, Signal, Slot, QEvent
from pathlib import Path
from langchainhandler import get_file_content_tuple

from pytalk.speaker import Speaker
import json
from util import generate_random_id,extract_json_string_from_llm
sys.path.append("../..")
sys.path.append("../../..")

from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtWidgets import QWidget, QApplication, QMessageBox, QMainWindow, QPushButton, QVBoxLayout,QTabWidget
from PyQt5.QtCore import pyqtSlot, Qt, QUrl, QFileInfo, pyqtProperty
from prompts import PromptDialog,PromptManager
from db.DBFactory import Session, Prompt,query_AgentTask_By_Id,delete_AgentTask,update_AgentTask,query_KMCfg_All,query_AiChatCfg_All,query_AIFriend_All,query_KMCfg,query_AiChatCfg,add_workflow_mng,get_prompt_by_title
from pluginsmanager.plugins_gui.tab_plugin import load_plugin
from noteeditor.msword import Main as NoteEditor
from file_manager import FileManager
import sys
from PyQt5.QtWidgets import (
    QApplication, QMainWindow, QLineEdit, QPushButton, QVBoxLayout, QWidget, QMenu, QAction, QHBoxLayout, QShortcut,QPlainTextEdit
)
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl, Qt
from PyQt5.QtGui import QKeySequence
from i18n import lt
class MessageHandler(QWidget):
    on_message = pyqtSignal(str)
    on_message_checked = pyqtSignal(int,str,str)
    on_edit_content_message  = pyqtSignal(str,str)
    on_message_file_clicked = pyqtSignal(str)
    on_message_open_link = pyqtSignal(str)
    on_message_copy_message = pyqtSignal(str)
    on_message_edit_message = pyqtSignal(str)
    on_message_delete_message = pyqtSignal(str)
    on_message_transfer_message = pyqtSignal(str)
    on_message_collect_message = pyqtSignal(str)
    on_message_toggle_parent_menu = pyqtSignal()
    on_message_task_run_code = pyqtSignal()
    on_message_task_next_step = pyqtSignal()
    on_message_task_exit = pyqtSignal()


    def __init__(self):
        super().__init__()
        self.theinnervalue = "cjrok"

    def PyQt52WebValue(self):
        return self.theinnervalue

    @pyqtSlot(str, result=str)
    def Web2PyQt5Value(self, tmpstr):
        self.theinnervalue = self.theinnervalue + tmpstr
        QMessageBox.information(self, "从网页来的信息", tmpstr)

    @pyqtSlot(int, str, str, result=str)
    def check_message(self,i,id,status):
        print("i:",i)
        print("id:", id)
        print("status",status)
        self.on_message_checked.emit(i,id,status)

    @pyqtSlot(str, str, result=str)
    def edit_content_message(self,code_type,text):
        print("codetype:",code_type)
        print("text:",text)
        self.on_edit_content_message.emit(code_type,text)

    @pyqtSlot(str, result=str)
    def file_clicked_message(self,file_path):
        print("file_path:",file_path)
        self.on_message_file_clicked.emit(file_path)

    @pyqtSlot(str, result=str)
    def open_link_message(self, url):
        print("url:", url)
        self.on_message_open_link.emit(url)

    @pyqtSlot(result=str)
    def toggle_parent_menu(self):
        self.on_message_toggle_parent_menu.emit()

    @pyqtSlot(str, result=str)
    def copy_message(self, data_id):
        print("data_id:", data_id)
        self.on_message_copy_message.emit(data_id)

    @pyqtSlot(str, result=str)
    def edit_message(self, data_id):
        print("data_id:", data_id)
        self.on_message_edit_message.emit(data_id)

    @pyqtSlot(str, result=str)
    def delete_message(self, data_id):
        print("data_id:", data_id)
        self.on_message_delete_message.emit(data_id)

    @pyqtSlot(str, result=str)
    def transfer_message(self, data_id):
        print("data_id:", data_id)
        self.on_message_transfer_message.emit(data_id)

    @pyqtSlot(str, result=str)
    def collect_message(self, data_id):
        print("data_id:", data_id)
        self.on_message_collect_message.emit(data_id)

    @pyqtSlot()
    def task_run_code(self):
        self.on_message_task_run_code.emit()

    @pyqtSlot()
    def task_next_step(self):
        self.on_message_task_next_step.emit()

    @pyqtSlot()
    def task_exit(self):
        self.on_message_task_exit.emit()

    def pass_message(self, messsage):
        self.on_message.emit(messsage)

    thevalue = pyqtProperty(str, fget=PyQt52WebValue, fset=Web2PyQt5Value)


class Ui_TaskPageWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(800, 600)
        TaskWidget.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        icon = QtGui.QIcon()
        icon.addFile("images/mail.png")
        TaskWidget.setWindowIcon(icon)
        self.vboxlayout = QtWidgets.QVBoxLayout(TaskWidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)  # 不留间隙

        # 创建一个水平布局并添加到类的属性中
        self.hboxlayoutlabel = QtWidgets.QHBoxLayout()

        # 创建左、中、右三个水平布局，用于分成三等分
        left_layout = QtWidgets.QHBoxLayout()
        center_layout = QtWidgets.QHBoxLayout()
        right_layout = QtWidgets.QHBoxLayout()

        # 左布局添加空白间隔项
        # left_layout.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum))

        # 根据任务类型设置标题标签的文本和图标路径

        title_texta = " " + self.name
        icon_patha = "images/llm.png"  # 假设群组图标的路径
        wa = 30
        ha = 21

        # 创建标题标签并设置样式
        self.title_labela = QLabel(lt("换模型","换模型","Select"), TaskWidget)
        self.title_labela.setCursor(Qt.PointingHandCursor)
        self.title_labela.mousePressEvent = self.on_label_click
        self.title_labela.setStyleSheet(
            "color: #146ebe; font-weight: bold; text-decoration: underline; border: solid 1px red"
        )
        self.title_labela.setFixedSize(50, 30)  # 设置固定大小以影响间隙
        self.title_labela.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        self.title_labela.setHidden(False)  # 确保title_labela可见

        # 创建模型标签并设置样式
        self.model_label = QLabel("", TaskWidget)  # 初始文本为空
        self.model_label.setStyleSheet("color: #909090;")
        self.model_label.setFixedHeight(30)  # 设置固定高度以影响间隙
        self.model_label.setContentsMargins(0, 0, 0, 0)  # 不留间隙

        # 将标题标签和模型标签放在一个新的水平布局中
        icon_and_title_layouta = QHBoxLayout()
        # icon_and_title_layouta.addWidget(self.title_labela, alignment=Qt.AlignRight)
        # icon_and_title_layouta.addWidget(self.model_label, alignment=Qt.AlignLeft)

        # 设置布局间隙和边距为零
        icon_and_title_layouta.setSpacing(0)
        icon_and_title_layouta.setContentsMargins(0, 0, 0, 0)
        # left_layout.addWidget(self.model_label, alignment=QtCore.Qt.AlignLeft)

        # spacerItem1a = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # icon_and_title_layouta.addItem(spacerItem1a)

        # self.place_holder_labela = QLabel("aa", TaskWidget)  # 初始文本为空
        # self.place_holder_labela.setStyleSheet("color: #909090;")
        # self.place_holder_labela.setFixedHeight(30)  # 设置固定高度以影响间隙
        # self.place_holder_labela.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        # icon_and_title_layouta.addWidget(self.place_holder_labela, alignment=QtCore.Qt.AlignLeft)

        left_layout.addWidget(self.title_labela)
        left_layout.addWidget(self.model_label)
        # left_layout.addLayout(icon_and_title_layouta)

        # 根据任务类型设置标题标签的文本和图标路径
        if self.task_type == 'single':
            title_text = " " + self.name
            icon_path = "images/agentsinglesm.png"
            w=18
            h=20
        else:
            title_text = " " + self.name
            icon_path = "images/agentmultism.png"  # 假设群组图标的路径
            w=26
            h=21

        # 创建图标标签并加载图标
        self.icon_label = QLabel("",TaskWidget)
        pixmap = QtGui.QPixmap(icon_path)
        self.icon_label.setPixmap(pixmap.scaled(w,h,1))  # 调整图标大小
        self.icon_label.setFixedHeight(30)  # 设置固定高度以影响间隙
        self.icon_label.setContentsMargins(0, 0, 0, 0)  # 不留间隙


        # 创建标题标签并设置样式
        self.title_label = QLabel(title_text, TaskWidget)
        self.title_label.setStyleSheet("color: #146ebe; font-weight: bold;")
        self.title_label.setFixedHeight(30)  # 设置固定高度以影响间隙
        self.title_label.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        self.title_label.setHidden(False)  # 确保title_label可见

        # 将图标标签和标题标签放在一个新的水平布局中
        icon_and_title_layout = QtWidgets.QHBoxLayout()
        icon_and_title_layout.addWidget(self.icon_label,alignment=QtCore.Qt.AlignRight)
        icon_and_title_layout.addWidget(self.title_label,alignment=QtCore.Qt.AlignLeft)
        icon_and_title_layout.setSpacing(0)  # 设置间隙为零
        icon_and_title_layout.setContentsMargins(0, 0, 0, 0)  # 设置边距为零

        # 将新的水平布局添加到中间布局中，并设置居中对齐
        center_layout.addLayout(icon_and_title_layout,stretch=0)

        # 创建模型标签并设置样式


        # 将模型标签添加到右边布局中
        self.place_holder_label = QLabel("", TaskWidget)  # 初始文本为空
        self.place_holder_label.setStyleSheet("color: #909090;")
        self.place_holder_label.setFixedHeight(30)  # 设置固定高度以影响间隙
        self.place_holder_label.setContentsMargins(0, 0, 0, 0)  # 不留间隙
        right_layout.addWidget(self.place_holder_label, alignment=QtCore.Qt.AlignRight)

        # 将三个子布局添加到主的水平布局中
        self.hboxlayoutlabel.addLayout(left_layout)
        self.hboxlayoutlabel.addLayout(center_layout)
        self.hboxlayoutlabel.addLayout(right_layout)

        # 将水平布局添加到垂直布局中
        self.vboxlayout.addLayout(self.hboxlayoutlabel)

        # 使用 QSplitter 来管理 self.frame 和 self.tabWidget
        self.splitter = QSplitter(Qt.Horizontal, TaskWidget)

        # self.messageBrowser = QtWidgets.QTextBrowser(TaskWidget)
        self.messageBrowser = QWebEngineView()
        self.messageBrowser.setObjectName("messageBrowser")

        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setStyleSheet("QFrame { border: 1px solid #c0c0c0;border-radius: 8px;}")
        self.frame_layout = QtWidgets.QVBoxLayout(self.frame)
        self.frame_layout.addWidget(self.messageBrowser)

        # 创建 QTabWidget 控件及其页签，设置页签在底部
        self.tabWidget = QTabWidget(self.splitter)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.South)

        self.tab_output = QtWidgets.QWidget()
        self.tab_output.setObjectName("tab_output")
        self.tabLayout_output = QtWidgets.QVBoxLayout(self.tab_output)
        self.tabLayout_output.setContentsMargins(0, 0, 0, 0)
        self.output_webview = QWebEngineView(self.tab_output)
        self.tabLayout_output.addWidget(self.output_webview)
        self.tabWidget.addTab(self.tab_output, "输出")

        self.tab_log = QtWidgets.QWidget()
        self.tab_log.setObjectName("tab_log")
        self.tabLayout_log = QVBoxLayout(self.tab_log)
        self.tabLayout_log.setContentsMargins(0, 0, 0, 0)
        self.textEdit_log = QtWidgets.QTextEdit(self.tab_log)
        self.textEdit_log.setReadOnly(True)
        self.tabLayout_log.addWidget(self.textEdit_log)
        self.tabWidget.addTab(self.tab_log, "日志")

        self.tab_file = FileManager()
        self.tab_file.setObjectName("tab_file")
        self.tabLayout_file = QVBoxLayout(self.tab_file)
        self.tabLayout_file.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.tab_file, "文件")


        self.splitter.setSizes([1, ])#设置初始状态不显示输出窗口

        self.vboxlayout.addWidget(self.splitter)

        # 内容菜单
        self.hboxlayout_content_menu = QHBoxLayout()
        self.content_menu_group_box = QGroupBox("")
        self.content_menu_group_box.setFixedHeight(100)
        self.content_menu_group_box.setVisible(False)

        self.hboxlayout_content_menu_inner = QHBoxLayout()

        spacerItem_content_menu = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout_content_menu_inner.addItem(spacerItem_content_menu)

        self.task_mode_checkboxa = QCheckBox("全选", TaskWidget)
        self.hboxlayout_content_menu_inner.addWidget(self.task_mode_checkboxa)
        self.task_mode_checkboxa.stateChanged.connect(self.toggle_page_all_checkboxes_status)



        self.delete_batch_button = QPushButton(TaskWidget)
        icon1a = QtGui.QIcon()
        icon1a.addFile("images/delete.png")
        self.delete_batch_button.setIcon(icon1a)
        self.delete_batch_button.setText("批量删除")
        self.delete_batch_button.clicked.connect(self.delete_message_batch)
        self.delete_batch_button.setObjectName("deletebatchButton")
        self.hboxlayout_content_menu_inner.addWidget(self.delete_batch_button)

        self.shareButton = QPushButton(TaskWidget)
        self.shareButton.setIcon(QtGui.QIcon("images/share.png"))
        self.shareButton.setObjectName("shareButton")
        self.shareButton.setText("合并转发")
        self.shareButton.clicked.connect(self.transfer_message_batch)
        self.hboxlayout_content_menu_inner.addWidget(self.shareButton)


        self.collectButton = QPushButton(TaskWidget)
        self.collectButton.setIcon(QtGui.QIcon("images/bookmark.png"))
        self.collectButton.setObjectName("collectButton")
        self.collectButton.setText("合并收藏")
        self.collectButton.clicked.connect(self.collect_message_batch)
        self.hboxlayout_content_menu_inner.addWidget(self.collectButton)

        self.workflowButton = QPushButton(TaskWidget)
        self.workflowButton.setIcon(QtGui.QIcon("images/workflow.png"))
        self.workflowButton.setObjectName("flowButton")
        self.workflowButton.setText("转为工作流")
        self.workflowButton.clicked.connect(self.workflow_button_click)
        self.hboxlayout_content_menu_inner.addWidget(self.workflowButton)






        self.close_button = QPushButton(TaskWidget)
        self.close_button.setText("X")
        self.close_button.setToolTip("关闭操作")
        self.close_button.setStyleSheet("""
                    QPushButton {
                        border-radius: 2px; /* 设置圆角 */
                        border: 1px solid #c0c0c0; /* 设置边框 */
                        background:#c0c0c0;
                        color:#146ebe;
                        width:40px;
                        height:40px;
                        font-size:16pt;
                    }
                        QPushButton:hover { /* 鼠标悬浮时的样式 */
                        background: #d3d3d3; /* 鼠标悬浮时按钮背景颜色变浅 */
                    }

                """)
        self.close_button.clicked.connect(lambda:self.toggle_content_menu("unchecked"))
        self.hboxlayout_content_menu_inner.addWidget(self.close_button)


        self.content_menu_group_box.setLayout(self.hboxlayout_content_menu_inner)

        self.hboxlayout_content_menu.addWidget(self.content_menu_group_box)
        spacerItem1_content_menu = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout_content_menu_inner.addItem(spacerItem1_content_menu)
        self.vboxlayout.addLayout(self.hboxlayout_content_menu)


        # 添加其他控件
        self.hboxlayout = QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)


        self.newButton = QPushButton(TaskWidget)
        self.newButton.setIcon(QtGui.QIcon("images/task.png"))
        self.newButton.setObjectName("newButton")
        self.hboxlayout.addWidget(self.newButton)


        self.attach_button = QPushButton(TaskWidget)
        icon1 = QtGui.QIcon()
        icon1.addFile("images/attachment.png")
        self.attach_button.setIcon(icon1)
        self.attach_button.setObjectName("fontButton")
        self.hboxlayout.addWidget(self.attach_button)

        self.kmButton = QPushButton(TaskWidget)
        self.kmButton.setIcon(QtGui.QIcon("images/km.png"))
        self.kmButton.setObjectName("kmButton")
        self.hboxlayout.addWidget(self.kmButton)

        self.plugin_button = QPushButton(TaskWidget)
        icon2 = QtGui.QIcon()
        icon2.addFile("images/plugin.png")
        self.plugin_button.setIcon(icon2)
        self.plugin_button.setObjectName("pluginButton")
        self.hboxlayout.addWidget(self.plugin_button)

        self.model_select_checkbox = QCheckBox("指定模型")
        #self.model_select_checkbox = QCheckBox("指定模型", TaskWidget)
        #self.hboxlayout.addWidget(self.model_select_checkbox)#暂时不添加了


        self.task_mode_checkbox = QCheckBox("任务模式", TaskWidget)
        self.hboxlayout.addWidget(self.task_mode_checkbox)

        self.history_mode_checkbox = QCheckBox("指定上下文", TaskWidget)
        self.hboxlayout.addWidget(self.history_mode_checkbox)

        self.prompt_combobox = QComboBox(TaskWidget)
        self.prompt_combobox.addItem("请选择提示词")
        self.prompt_combobox.addItem("a.你是个资深的程序员")
        self.prompt_combobox.addItem("b.你是个资深的架构师")
        self.hboxlayout.addWidget(self.prompt_combobox)

        self.manage_button = QPushButton("管理", TaskWidget)
        self.manage_button.setToolTip("右击该按钮可置入对应对话模板")
        self.hboxlayout.addWidget(self.manage_button)

        # 添加 "输出" QCheckBox
        self.output_checkbox = QCheckBox(lt("Side Pane|边窗"), TaskWidget)
        self.output_checkbox.stateChanged.connect(self.toggle_output_checkbox)
        self.output_checkbox.setChecked(False)
        self.hboxlayout.addWidget(self.output_checkbox)

        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout)

        self.hboxlayout1 = QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.messageEdit = QtWidgets.QTextEdit(TaskWidget)
        self.messageEdit.setAcceptRichText(False)#设置为不接受富文本，否则格式特别是背景总数很混乱
        self.messageEdit.setPlaceholderText("Ctrl+/可以调出插件")
        self.messageEdit.setFixedHeight(45)  # 假设每行高度为20像素
        self.messageEdit.setStyleSheet("""

            QTextEdit {
            border: 1px solid #c0c0c0; /* 边框颜色 */
            border-radius: 8px;       /* 圆角半径 */
            padding: 2px;              /* 内边距 */
            /*background-color: #ffffff;*/ /* 背景颜色 */
        }
            QTextEdit:focus {
                border-color: #61addf; /* 设置焦点时的边框颜色 */
            }
        """)

        self.messageEdit.setObjectName("messageEdit")
        self.messageEdit.textChanged.connect(self.adjustHeight)
        self.hboxlayout1.addWidget(self.messageEdit)

        self.sendButton = QPushButton(TaskWidget)
        icon3 = QtGui.QIcon()
        icon3.addFile("images/sendmessage.png")
        self.sendButton.setIcon(icon3)
        self.sendButton.setObjectName("sendButton")
        self.hboxlayout1.addWidget(self.sendButton)
        self.vboxlayout.addLayout(self.hboxlayout1)


        self.stopButton = QPushButton(TaskWidget)
        icon3 = QtGui.QIcon()
        icon3.addFile("images/stop.png")
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.hboxlayout1.addWidget(self.stopButton)
        self.stopButton.setVisible(False)




        self.retranslateUi(TaskWidget)

        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

        self.remaining_attachments = 0  # 初始化可见附件计数

    def adjustHeight(self):
        line_height = 20  # 每行高度为20像素
        min_height = 40  # 最小高度为40像素
        max_height = 200  # 最大高度为90像素
        print("in adjustHeight")

        # 计算文本行数
        document = self.messageEdit.document()
        document_height = document.size().height()
        lines = int(document_height / line_height)

        # 计算新的高度
        new_height = max(min_height, min(max_height, lines * line_height))

        # 设置新的高度
        self.messageEdit.setFixedHeight(new_height+5)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Message"))
        print("go setting")
        #         self.messageBrowser.setHtml(_translate("TaskWidget", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        # "p, li { white-space: pre-wrap; }\n"
        # "</style></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:14pt; font-weight:400; font-style:normal;background-color: #f0f0f0;border:\'solid 1px red;\' \">"
        # "</body></html>"))

        # self.messageBrowser.setHtml(QtCore.QCoreApplication.translate("TaskWidget", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        #                                                                                "p, li { white-space: pre-wrap; }\n"
        #                                                                                "</style><script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/1.4.4/jquery.min.js' type='text/javascript'></script><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/default.min.css'><script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/highlight.min.js'></script></head><body style=\" font-family:\'Microsoft YaHei\'; font-size:14pt; font-weight:400; font-style:normal;background-color: #f0f0f0;border:\'solid 1px red;\' \">"
        #                                                                                "<script>hljs.highlightAll();</script></body></html>"))

        file_path = os.path.join(Path(__file__).resolve().parent.parent, "scripts", "taskpagemsgbox.html")
        # file_path = os.path.join(Path(__file__).resolve().parent.parent, "scripts", "index3.html")
        print(file_path)
        url_string = QUrl.fromLocalFile(file_path)
        # url_string = urllib.request.pathname2url(os.path.join(Path(__file__).resolve().parent.parent, "scripts", "taskpagemsgbox.html"))
        print("transform")
        print(url_string)
        # self.messageBrowser.page().load(url_string)
        mind_path="C:\\dev\\ai-sns\\PyTalk\\mindmap.html"
        mind_path = "C:\\dev\\ai-sns\\PyTalk\\pytalk\\coding\\mycode_workflow.html"
        mind_url_string = QUrl.fromLocalFile(mind_path)
        # mind_url_string = QUrl("https://examples.logic-flow.cn/demo/dist/organizer")
        # mind_url_string = QUrl("https://sebastien.drouyer.com/jquery.flowchart-demo/")
        #
        # self.output_webview.page().load(mind_url_string)
        print("url_string:",url_string)
        print("mind_url_string:", mind_url_string)

        print(self.output_webview.settings().defaultSettings())
        self.output_webview.settings().setAttribute(QWebEngineSettings.PluginsEnabled, True)

        # 显示开发者工具
        self.output_webview.page().runJavaScript('console.log("Opening DevTools");')
        self.output_webview.show()
        self.output_webview.page().profile().setPersistentStoragePath("<your_storage_path>")
        self.output_webview.page().setDevToolsPage(self.output_webview.page())  # 允许开发者工具
        # self.output_webview.page().devToolsPage() # 显示开发者工具
        self.output_webview.page().load(mind_url_string)

        self.messageBrowser.page().load(url_string)
        global channel
        global message_handler
        channel = QWebChannel()
        message_handler = MessageHandler()
        self.message_handler = message_handler
        self.channel = channel
        channel.registerObject("message_handler", message_handler)

        # self.messageBrowser.page().setWebChannel(channel)
        self.messageBrowser.page().setWebChannel(channel)


        message_handler.on_message_checked.connect(self.set_selected_history_index)
        message_handler.on_edit_content_message.connect(self.edit_selected_content)
        message_handler.on_message_file_clicked.connect(self.attachment_clicked)
        message_handler.on_message_open_link.connect(self.open_link)
        message_handler.on_message_copy_message.connect(self.copy_message)
        message_handler.on_message_edit_message.connect(self.edit_message)
        message_handler.on_message_delete_message.connect(self.delete_message)
        message_handler.on_message_transfer_message.connect(self.transfer_message)
        message_handler.on_message_collect_message.connect(self.collect_message)
        message_handler.on_message_toggle_parent_menu.connect(self.toggle_content_menu)
        message_handler.on_message.connect(self.on_message_from_message_handler)
        message_handler.on_message_task_run_code.connect(self.task_run_code)
        message_handler.on_message_task_next_step.connect(self.task_next_step)
        message_handler.on_message_task_exit.connect(self.task_exit)

        self.speaker = Speaker(message_handler, self.messageBrowser)
        self.speaker.on_message_ask_for_feedback.connect(self.save_task_output)



        # file_path = os.path.join(Path(__file__).resolve().parent, "scripts", "taskpagemsgbox.html")
        # url_string = QUrl.fromLocalFile(file_path)
        # web_browser.page().load(url_string)

        # self.messageBrowser.page().load(url_string)

        # self.messageBrowser.setHtml(QtCore.QCoreApplication.translate("TaskWidget",thehtml))

        # self.shared=shared

        self.newButton.setText(_translate("TaskWidget", "新对话"))
        self.attach_button.setText(_translate("TaskWidget", "附件"))
        self.kmButton.setText(_translate("TaskWidget", "知识库"))
        self.plugin_button.setText(_translate("TaskWidget", "插件"))
        self.sendButton.setText(_translate("TaskWidget", "发送"))
        self.stopButton.setText(_translate("TaskWidget", "停止"))
        # self.sendButton.setShortcut(_translate("TaskWidget", "Return"))
        # self.sendButton.setShortcut(QtGui.QKeySequence(Qt.Key_Return))
        self.sendButton.setShortcut(QtGui.QKeySequence(Qt.ControlModifier + Qt.Key_Return))


        #search 相关
        self.messageBrowser.setContextMenuPolicy(Qt.CustomContextMenu)
        self.messageBrowser.customContextMenuRequested.connect(self.show_context_menu)

        self.search_box = SearchBox(self)
        self.search_box.setPlaceholderText("在此输入搜索词")
        self.search_box.setVisible(False)
        self.search_box.returnPressed.connect(self.search_in_page)
        self.search_box.setStyleSheet("""
                            QLineEdit {
                                border: 1px solid #ccc;
                                border-radius: 10px;
                                padding: 2px 8px;
                                background: #fff;
                                selection-background-color: #0078d7;
                            }
                        """)

        self.search_button = QPushButton("×")
        self.search_button.clicked.connect(self.toggle_search_box)
        self.search_button.setVisible(False)
        self.search_button.setStyleSheet("""
                            QPushButton {
                                border: none;
                                background: transparent;
                                font-weight: bold;
                            }
                            QPushButton:hover {
                                color: #ff0000;
                            }
                        """)

        self.shortcut = QShortcut(QKeySequence('Ctrl+F'), self)
        self.shortcut.activated.connect(self.toggle_search_box)

        # 将搜索框放置在 QWebEngineView 的右上角
        self.search_container = QWidget(self.messageBrowser)
        self.search_container.setFixedSize(250, 30)
        self.search_container.move(self.messageBrowser.width() - 270, 10)  # 定位到右上角
        self.search_container.setVisible(True)

        search_layout = QHBoxLayout()
        search_layout.addWidget(self.search_box)
        search_layout.addWidget(self.search_button)
        search_layout.setContentsMargins(0, 0, 0, 0)  # 去除边距
        self.search_container.setLayout(search_layout)

    def on_label_click(self, event):
        """处理 QLabel 点击事件，调用打开对话框的函数"""
        if event.button() == 1:  # 检查是否为左键点击
            self.opendialogplugin()

    def attachment_clicked(self,file_path):
        print(file_path)
        main_directory = os.getcwd()

        # 定义相对路径
        relative_path = file_path

        # 构建绝对路径
        absolute_path = os.path.abspath(os.path.join(main_directory, relative_path))

        print(f"Absolute path: {absolute_path}")

        self.open_file(absolute_path)


    def toggle_output_checkbox(self, state):
        self.check_if_scrolled_to_top()

        if state == Qt.Checked:
            self.splitter.setSizes([300, 1])
        else:
            self.splitter.setSizes([1, ])

    def check_if_scrolled_to_top(self):
        # 使用 JavaScript 检查当前滚动位置是否为 0
        script = """
            (function() {
                try {
                    var scrolledToTop = (window.scrollY === 0);
                    return scrolledToTop;
                } catch (e) {
                    console.log(e);
                    return false;
                }
            })();
        """
        self.messageBrowser.page().runJavaScript(script, self.handle_scroll_check_result)

    def handle_scroll_check_result(self, result):
        # 处理 JavaScript 返回的结果
        if result is None:
            print("JavaScript execution returned None. Please check the script for errors.")
        elif result:
            print("The webpage is scrolled to the top.")
        else:
            print("The webpage is not scrolled to the top.")


    def toggle_chat_mode(self, state):

        if state == QtCore.Qt.Checked:
            self.agent.chat_mode = 'task'
        else:
            self.agent.chat_mode = 'chat'

    def toggle_history_mode(self, state):

        if state == QtCore.Qt.Checked:
            self.agent.history_mode = 'specify'
            self.messageBrowser.page().runJavaScript('displayCheckboxes();')
        else:
            self.agent.history_mode = 'all'
            self.messageBrowser.page().runJavaScript('setAllCheckboxesChecked(false);')
            self.messageBrowser.page().runJavaScript('hideCheckboxes();')


    def set_prompt_string(self, index):
        # if index>0:
        #     self.agent.current_prompt = self.prompt_combobox.itemText(index)
        # else:
        #     self.agent.current_prompt = ""
        title = self.prompt_combobox.currentText()
        content = self.prompt_combobox.currentData()
        print(f"Title: {title}, Content: {content}")
        self.system_role_prompt = content

        # title = self.prompt_combobox.currentText()
        # session = Session()
        # record = session.query(Prompt).filter(Prompt.title == title).first()
        # if record:
        #     q_template = record.question
        #     if q_template:
        #         # self.messageEdit.setPlainText(q_template+self.messageEdit.toPlainText())
        #         # self.messageEdit.insertPlainText(q_template)
        #         cursor = self.messageEdit.textCursor()
        #         cursor.movePosition(cursor.Start)
        #
        #         # Insert the text
        #         cursor.insertText(q_template)
        #         self.messageEdit.setTextCursor(cursor)







    def toggle_model_select_type(self, state):
        if state == QtCore.Qt.Checked:
            self.agent.model_select_type = 'specify'
        else:
            self.agent.model_select_type = 'auto'

    def on_manage_button_clicked(self):
        print("hello")
        print("model_label-->",self.model_label.text())
        self.prompt_manager = PromptManager(self,self.model_label.text())
        self.prompt_manager.exec_()

    def receive_template(self, template_content):
            q_template = template_content
            cursor = self.messageEdit.textCursor()
            cursor.movePosition(cursor.Start)
            # Insert the text
            cursor.insertText(q_template)
            self.messageEdit.setTextCursor(cursor)







    def manage_button_mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.on_manage_button_clicked()
        elif event.button() == Qt.RightButton:
        # if event.button() == Qt.RightButton:
            # 处理模板的添加
            title = self.prompt_combobox.currentText()
            session = Session()
            record = session.query(Prompt).filter(Prompt.title == title).first()
            if record:
                q_template = record.question
                if q_template:
                    # self.messageEdit.setPlainText(q_template+self.messageEdit.toPlainText())
                    # self.messageEdit.insertPlainText(q_template)
                    cursor = self.messageEdit.textCursor()
                    cursor.movePosition(cursor.Start)

                    # Insert the text
                    cursor.insertText(q_template)
                    self.messageEdit.setTextCursor(cursor)

        if event.modifiers() == Qt.ShiftModifier:
            print("shiftclick")

    def update_prompts_in_combobox(self):
        current_value = self.prompt_combobox.currentText()
        self.prompt_combobox.clear()
        session = Session()
        prompts = session.query(Prompt).all()
        for prompt in prompts:
            self.prompt_combobox.addItem(prompt.title, prompt.content)
        session.close()

        index = self.prompt_combobox.findText(current_value)
        if index != -1:
            self.prompt_combobox.setCurrentIndex(index)

    def print_selected_prompt(self):
        title = self.prompt_combobox.currentText()
        content = self.prompt_combobox.currentData()
        print(f"Title: {title}, Content: {content}")

    #webpage serch

    def show_context_menu(self, position):
        context_menu = QMenu()

        selected_text = self.messageBrowser.page().selectedText()

        if selected_text:

            if self.is_url(selected_text):
                print("is link")
                open_link_action = QAction("打开链接", self)
                open_link_action.triggered.connect(lambda: self.open_link(selected_text))
                context_menu.addAction(open_link_action)

            explain_action = QAction("解释选中内容", self)
            explain_action.triggered.connect(lambda: self.explain_text(selected_text))
            context_menu.addAction(explain_action)

            copy_action = QAction("拷贝(Ctrl+C)", self)
            copy_action.triggered.connect(self.copy_text)
            context_menu.addAction(copy_action)



            print("selected_text:", selected_text)

        search_action = QAction("搜索(Ctrl+F1)", self)
        search_action.triggered.connect(self.toggle_search_box)
        context_menu.addAction(search_action)

        # 将搜索选项移到“拷贝”和“打开链接”下面
        actions = context_menu.actions()
        if len(actions) > 1:
            actions[0], actions[1] = actions[1], actions[0]

        context_menu.exec_(self.messageBrowser.mapToGlobal(position))

    def copy_text(self):
        self.messageBrowser.triggerPageAction(QWebEnginePage.Copy)

    def open_link(self, url):
        cleaned_url = url.strip()
        print("cleaned_url:",cleaned_url)
        if not (cleaned_url[-20:]=="taskpagemsgbox.html#"):#排除文件链接
            webbrowser.open(cleaned_url)

    def copy_message(self, data_id):
        type_str=data_id[-1]
        record_id=data_id[3:]
        record_id=record_id[0:-2]
        record=query_AgentTask_By_Id(record_id)
        if type_str=="a":
            message=record.problem
        else:
            message=record.answer
        pyperclip.copy(message)
    def edit_message(self, data_id):
        type_str = data_id[-1]
        record_id = data_id[3:]
        record_id = record_id[0:-2]
        record = query_AgentTask_By_Id(record_id)
        if type_str == "a":
            message = record.problem
        else:
            message = record.answer
        self.messageEdit.setPlainText(message)

    def delete_message(self, data_id):
        reply = QMessageBox.question(self, '删除确定',
                                     f"您确定要删除吗?",
                                     QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        if reply == QMessageBox.Yes:
            type_str = data_id[-1]
            record_id = data_id[3:]
            record_id = record_id[0:-2]
            record = query_AgentTask_By_Id(record_id)
            if type_str == "a":
                message = record.answer
                if message=="":
                    delete_AgentTask(int(record_id))
                else:
                    update_AgentTask(int(record_id),problem="")
            else:
                message = record.problem
                if message=="":
                    delete_AgentTask(int(record_id))
                else:
                    update_AgentTask(int(record_id),answer="")

    def delete_message_batch(self):
        reply = QMessageBox.question(self, '删除确定',
                                     f"您确定要删除吗?",
                                     QMessageBox.Yes | QMessageBox.No, QMessageBox.Yes)
        if reply == QMessageBox.Yes:
            for data_id in self.selected_history_id:
                type_str = data_id[-1]
                record_id = data_id[3:]
                record_id = record_id[0:-2]
                record = query_AgentTask_By_Id(record_id)
                if type_str == "a":
                    message = record.answer
                    if message=="":
                        delete_AgentTask(int(record_id))
                    else:
                        update_AgentTask(int(record_id),problem="")
                else:
                    message = record.problem
                    if message=="":
                        delete_AgentTask(int(record_id))
                    else:
                        update_AgentTask(int(record_id),answer="")

                browser_page=self.messageBrowser.page()

                browser_page.runJavaScript('dataId=`' + data_id + '`')
                browser_page.runJavaScript('deleteMessageById(dataId)')

    def task_run_code(self):
        message="ok"
        self.messageEdit.setPlainText(message)
        self.sendMessage()

    def task_next_step(self):
        message="exit"
        self.messageEdit.setPlainText(message)
        self.sendMessage()

    def task_exit(self):
        message="exit"
        self.messageEdit.setPlainText(message)
        # self.sendMessage()

    def update_contact_combobox(self,forwardComboBox,contactComboBox):
        """根据forwardComboBox的值更新contactComboBox的选项"""
        current_text = forwardComboBox.currentText()
        current_data = forwardComboBox.currentData()
        # 清空现有选项
        contactComboBox.clear()

        # 根据forwardComboBox的选择设置contactComboBox的选项
        records = query_AIFriend_All(owner_sns_account=current_data)
        for record in records:
            contactComboBox.addItem(record.nickname, record.account)

    def transfer_message(self, data_id):
        type_str = data_id[-1]
        record_id = data_id[3:]
        record_id = record_id[0:-2]
        record = query_AgentTask_By_Id(record_id)
        if type_str == "a":
            message = record.problem
        else:
            message = record.answer



        transfer_dialog = QDialog()
        dialog = QDialog()
        dialog.setWindowTitle("请选择要转发给哪个帐号的联系人")
        dialog.setMinimumWidth(500)  # 设置对话框的最小宽度

        # 创建主垂直布局
        main_layout = QVBoxLayout()

        # 创建表单布局：用于整洁地排列标签和输入部件
        form_layout = QFormLayout()

        # 创建组合框和标签
        dialog.forwardComboBox = QComboBox()
        records = query_AiChatCfg_All(is_delete=0)
        for record in records:
            dialog.forwardComboBox.addItem(record.nickname,record.account)

        form_layout.addRow("AI社交帐号：", dialog.forwardComboBox)

        # 创建选择联系人组合框和标签
        dialog.contactComboBox = QComboBox()
        self.update_contact_combobox(dialog.forwardComboBox, dialog.contactComboBox)  # 初始化联系人组合框
        form_layout.addRow("该帐号联系人：", dialog.contactComboBox)

        dialog.forwardComboBox.currentIndexChanged.connect(lambda: self.update_contact_combobox(dialog.forwardComboBox, dialog.contactComboBox))

        # 创建单行文本编辑器和标签
        dialog.descriptionEdit = QLineEdit()
        form_layout.addRow("转发说明：", dialog.descriptionEdit)

        # 将表单布局添加到主布局
        main_layout.addLayout(form_layout)

        # 创建水平布局用于按钮
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)  # 添加弹性空间，使按钮靠右对齐

        ok_button = QPushButton("确定")
        cancel_button = QPushButton("取消")
        ok_button.clicked.connect(dialog.accept)
        cancel_button.clicked.connect(dialog.reject)

        # 将按钮添加到水平布局
        button_layout.addWidget(ok_button)
        button_layout.addWidget(cancel_button)

        # 将按钮布局添加到主布局
        main_layout.addLayout(button_layout)

        # 设置主布局
        dialog.setLayout(main_layout)

        if dialog.exec_():
            # selected_ai_account = dialog.forwardComboBox.currentText()
            # selected_contact = dialog.contactComboBox.currentText()
            selected_ai_account = dialog.forwardComboBox.currentData()
            selected_contact = dialog.contactComboBox.currentData()
            description = dialog.descriptionEdit.text()
            print(f"Selected AI Account: {selected_ai_account}, Contact: {selected_contact}, Description: {description}, Message:{message}")
            record=query_AiChatCfg(account=selected_ai_account)
            user_id=record.user_id
            application=self.application
            buddyList =  application.buddylist_list[user_id]
            buddyList.send_message(selected_contact, message)

    def transfer_message_batch(self):
        message_batch=""
        for data_id in self.selected_history_id:
            type_str = data_id[-1]
            record_id = data_id[3:]
            record_id = record_id[0:-2]
            record = query_AgentTask_By_Id(record_id)
            if type_str == "a":
                message = record.problem
            else:
                message = record.answer

            message_batch = message_batch + message + "\n"





        transfer_dialog = QDialog()
        dialog = QDialog()
        dialog.setWindowTitle("请选择要转发给哪个帐号的联系人")
        dialog.setMinimumWidth(500)  # 设置对话框的最小宽度

        # 创建主垂直布局
        main_layout = QVBoxLayout()

        # 创建表单布局：用于整洁地排列标签和输入部件
        form_layout = QFormLayout()

        # 创建组合框和标签
        dialog.forwardComboBox = QComboBox()
        records = query_AiChatCfg_All(is_delete=0)
        for record in records:
            dialog.forwardComboBox.addItem(record.nickname,record.account)

        form_layout.addRow("AI社交帐号：", dialog.forwardComboBox)

        # 创建选择联系人组合框和标签
        dialog.contactComboBox = QComboBox()
        self.update_contact_combobox(dialog.forwardComboBox, dialog.contactComboBox)  # 初始化联系人组合框
        form_layout.addRow("该帐号联系人：", dialog.contactComboBox)

        dialog.forwardComboBox.currentIndexChanged.connect(lambda: self.update_contact_combobox(dialog.forwardComboBox, dialog.contactComboBox))

        # 创建单行文本编辑器和标签
        dialog.descriptionEdit = QLineEdit()
        form_layout.addRow("转发说明：", dialog.descriptionEdit)

        # 将表单布局添加到主布局
        main_layout.addLayout(form_layout)

        # 创建水平布局用于按钮
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)  # 添加弹性空间，使按钮靠右对齐

        ok_button = QPushButton("确定")
        cancel_button = QPushButton("取消")
        ok_button.clicked.connect(dialog.accept)
        cancel_button.clicked.connect(dialog.reject)

        # 将按钮添加到水平布局
        button_layout.addWidget(ok_button)
        button_layout.addWidget(cancel_button)

        # 将按钮布局添加到主布局
        main_layout.addLayout(button_layout)

        # 设置主布局
        dialog.setLayout(main_layout)

        if dialog.exec_():
            # selected_ai_account = dialog.forwardComboBox.currentText()
            # selected_contact = dialog.contactComboBox.currentText()
            selected_ai_account = dialog.forwardComboBox.currentData()
            selected_contact = dialog.contactComboBox.currentData()
            description = dialog.descriptionEdit.text()
            print(f"Selected AI Account: {selected_ai_account}, Contact: {selected_contact}, Description: {description}, Message:{message_batch}")
            record=query_AiChatCfg(account=selected_ai_account)
            user_id=record.user_id
            application=self.application
            buddyList =  application.buddylist_list[user_id]
            buddyList.send_message(selected_contact, message_batch)

    def collect_message(self, data_id):
        type_str = data_id[-1]
        record_id = data_id[3:]
        record_id = record_id[0:-2]
        record = query_AgentTask_By_Id(record_id)
        if type_str == "a":
            message = record.problem
        else:
            message = record.answer

        transfer_dialog = QDialog()
        transfer_dialog.setWindowTitle("收藏")
        transfer_dialog.setMinimumWidth(500)  # 设置对话框的最小宽度

        # 创建主垂直布局
        main_layout = QVBoxLayout()

        # 创建表单布局：用于整洁地排列标签和输入部件
        form_layout = QFormLayout()

        # 创建组合框和标签
        transfer_dialog.comboBox = QComboBox()
        transfer_dialog.comboBox.setEditable(True)
        records = query_KMCfg_All(kmtype="1")
        for record in records:
            transfer_dialog.comboBox.addItem(record.name)

        # transfer_dialog.populate_combobox()
        form_layout.addRow("收藏至笔记：", transfer_dialog.comboBox)

        # 创建组合框和标签
        transfer_dialog.comboBox_label = QComboBox()
        transfer_dialog.comboBox_label.setEditable(True)
        records = query_KMCfg_All(kmtype="1")
        for record in records:
            transfer_dialog.comboBox_label.addItem(record.name)

        # transfer_dialog.populate_combobox()
        form_layout.addRow("标签：", transfer_dialog.comboBox_label)

        # 创建单行文本编辑器和标签
        transfer_dialog.titleEdit = QLineEdit()
        form_layout.addRow("标题：", transfer_dialog.titleEdit)

        # 将表单布局添加到主布局
        main_layout.addLayout(form_layout)

        # 创建水平布局用于按钮
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)  # 添加弹性空间，使按钮靠右对齐

        ok_button = QPushButton("确定")
        cancel_button = QPushButton("取消")
        ok_button.clicked.connect(transfer_dialog.accept)
        cancel_button.clicked.connect(transfer_dialog.reject)

        # 将按钮添加到水平布局
        button_layout.addWidget(ok_button)
        button_layout.addWidget(cancel_button)

        # 将按钮布局添加到主布局
        main_layout.addLayout(button_layout)

        # 设置主布局
        transfer_dialog.setLayout(main_layout)

        if transfer_dialog.exec_():
            # 在对话框被接受时执行的代码
            selected_note = transfer_dialog.comboBox.currentText()
            selected_label = transfer_dialog.comboBox_label.currentText()
            title = transfer_dialog.titleEdit.text()
            print(f"Selected Note: {selected_note}, selected_label: {selected_label}, Title: {title}, Message:{message}")

            km_cfg=query_KMCfg(name=selected_note)
            note_editor = NoteEditor(self.application)
            note_editor.setObjectName('NoteEditorObject')
            # note_editor.show()
            note_editor.record_id = 0
            note_editor.km_id = km_cfg.km_id
            note_editor.km_cfg = km_cfg
            note_editor.loadFile()
            note_editor.text.setText(message)
            note_editor.save(title)
            QMessageBox.information(self, "信息", "收藏成功!")

    def collect_message_batch(self):
        message_batch = ""
        for data_id in self.selected_history_id:
            type_str = data_id[-1]
            record_id = data_id[3:]
            record_id = record_id[0:-2]
            record = query_AgentTask_By_Id(record_id)
            if type_str == "a":
                message = record.problem
            else:
                message = record.answer

            message_batch = message_batch + message + "\n"

        transfer_dialog = QDialog()
        transfer_dialog.setWindowTitle("收藏")
        transfer_dialog.setMinimumWidth(500)  # 设置对话框的最小宽度

        # 创建主垂直布局
        main_layout = QVBoxLayout()

        # 创建表单布局：用于整洁地排列标签和输入部件
        form_layout = QFormLayout()

        # 创建组合框和标签
        transfer_dialog.comboBox = QComboBox()
        transfer_dialog.comboBox.setEditable(True)
        records = query_KMCfg_All(kmtype="1")
        for record in records:
            transfer_dialog.comboBox.addItem(record.name)

        # transfer_dialog.populate_combobox()
        form_layout.addRow("收藏至笔记：", transfer_dialog.comboBox)

        # 创建组合框和标签
        transfer_dialog.comboBox_label = QComboBox()
        transfer_dialog.comboBox_label.setEditable(True)
        records = query_KMCfg_All(kmtype="1")
        for record in records:
            transfer_dialog.comboBox_label.addItem(record.name)

        # transfer_dialog.populate_combobox()
        form_layout.addRow("标签：", transfer_dialog.comboBox_label)

        # 创建单行文本编辑器和标签
        transfer_dialog.titleEdit = QLineEdit()
        form_layout.addRow("标题：", transfer_dialog.titleEdit)

        # 将表单布局添加到主布局
        main_layout.addLayout(form_layout)

        # 创建水平布局用于按钮
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)  # 添加弹性空间，使按钮靠右对齐

        ok_button = QPushButton("确定")
        cancel_button = QPushButton("取消")
        ok_button.clicked.connect(transfer_dialog.accept)
        cancel_button.clicked.connect(transfer_dialog.reject)

        # 将按钮添加到水平布局
        button_layout.addWidget(ok_button)
        button_layout.addWidget(cancel_button)

        # 将按钮布局添加到主布局
        main_layout.addLayout(button_layout)

        # 设置主布局
        transfer_dialog.setLayout(main_layout)

        if transfer_dialog.exec_():
            # 在对话框被接受时执行的代码
            selected_note = transfer_dialog.comboBox.currentText()
            selected_label = transfer_dialog.comboBox_label.currentText()
            title = transfer_dialog.titleEdit.text()
            print(f"Selected Note: {selected_note}, selected_label: {selected_label}, Title: {title}, Message:{message_batch}")

            km_cfg=query_KMCfg(name=selected_note)
            note_editor = NoteEditor(self.application)
            note_editor.setObjectName('NoteEditorObject')
            # note_editor.show()
            note_editor.record_id = 0
            note_editor.km_id = km_cfg.km_id
            note_editor.km_cfg = km_cfg
            note_editor.loadFile()
            note_editor.text.setText(message_batch)
            note_editor.save(title)
            QMessageBox.information(self, "信息", "收藏成功!")

    def message_to_node(self, message, type_str, index):
        """
        将消息转换为工作流中的一个节点。
        :param message: 消息文本
        :param type_str: 消息类型字符串
        :param index: 节点的索引值
        :return: 节点的字典表示
        """
        node_id = f"node_{index}"
        # 构建节点结构
        node = {
            "id": node_id,  # 节点ID
            "title": message,  # 节点的标题是消息本身
            "type": "message_node",  # 节点类型
            "type_str": type_str,  # 节点类型字符串
            "description": message,  # 描述信息同样是消息
            "plugin": "",  # 插件字段（根据需要填写）
            "connectors": []  # 暂未实现具体连接器
        }
        return node

    def transfer_message_to_workflow(self, workflow_json_str):
        """
                转换选定历史记录中的消息为工作流节点和连接器。
        """
        if "```json" in workflow_json_str:
            workflow_json_str = extract_json_string_from_llm(workflow_json_str)


        # 定义常量
        NODE_SIZE = 120  # 节点的边长
        NODE_DISTANCE = 200  # 节点之间的距离
        workflow_nodes = []  # 用于存储工作流节点的列表
        connectors = []  # 用于存储连接器的列表

        # 将 JSON 字符串转换为 Python 字典对象

        # 转换 JSON 字符串为字典对象
        workflow_json = json.loads(workflow_json_str)
        # 判断 workflow_json 是列表还是字典
        if isinstance(workflow_json, list):
            # 如果 workflow_json 是一个列表
            print("workflow_json is a list")
            nodes = workflow_json
        elif isinstance(workflow_json, dict):
            # 如果 workflow_json 是一个字典
            print("workflow_json is a dictionary")
            nodes = workflow_json.get('workflow', None)
        else:
            # 如果 workflow_json 既不是列表也不是字典
            print("workflow_json is neither a list nor a dictionary")


        last_node = nodes[-1]

        if last_node["type"]!="end":
            l = len(nodes)
            end_node_id = "node"+str(l)
            nodes.append({
                "id": f"{end_node_id}",
                "title": "任务结束",
                "description": "任务执行完毕。",
                "type": "end",
                "type_str": "结束",
                "plugin": ""
                    })

        # 为每个节点添加坐标和连接器
        for index, node in enumerate(nodes):
            # 计算节点坐标
            node['x'] = index * (NODE_DISTANCE + NODE_SIZE)
            node['y'] = 100  # 所有节点在同一水平线上

            # 计算连接器坐标
            cx = node['x'] + NODE_SIZE / 2
            cy = node['y'] + NODE_SIZE / 2
            node['connectors'] = [
                {"cx": cx, "cy": (cy - NODE_SIZE / 2) - 10},
                {"cx": cx + (NODE_SIZE / 2) + 10, "cy": cy},
                {"cx": cx, "cy": cy + (NODE_SIZE / 2) + 10},
                {"cx": cx - (NODE_SIZE / 2) - 10, "cy": cy}
            ]

            # 创建连接器，如果不是第一个节点，连接到前一个节点
            if index > 0:
                connectors.append({
                    "connector1Id": f"node{index}",
                    "connector2Id": f"node{index + 1}",
                    "connector1Index": 1,
                    "connector2Index": 3
                })

        # 输出结果
        print(json.dumps(nodes, ensure_ascii=False, indent=2))
        workflow_cfg = {"nodes":nodes,"lines":connectors}
        detail=json.dumps(workflow_cfg, ensure_ascii=False, indent=4)
        title = self.work_flow_title
        selected_label = self.work_flow_label
        desc = self.work_flow_desc
        workflow_id = generate_random_id()
        add_workflow_mng(workflow_id=workflow_id, title=title, description=desc, workflow_tags=selected_label, detail=detail, timer_desc="", timer_cron="")

        QMessageBox.information(self, "信息", "转为工作流成功,请到工作流模块中查看您转过去的工作流。")
        # 恢复原来状态
        self.is_transfer_to_workflow = False  # 恢复状态
        self.system_role_prompt = self.pre_system_role_prompt
        self.pre_system_role_prompt = ""
        self.work_flow_title = ""
        self.work_flow_label = ""
        self.work_flow_desc = ""

    def workflow_button_click(self):


        transfer_dialog = QDialog()
        transfer_dialog.setWindowTitle("转为工作流")
        transfer_dialog.setMinimumWidth(500)  # 设置对话框的最小宽度

        # 创建主垂直布局
        main_layout = QVBoxLayout()

        # 创建表单布局：用于整洁地排列标签和输入部件
        form_layout = QFormLayout()

        # 创建单行文本编辑器和标签
        transfer_dialog.titleEdit = QLineEdit()
        form_layout.addRow("标题：", transfer_dialog.titleEdit)

        # 创建组合框和标签
        transfer_dialog.comboBox_label = QComboBox()
        transfer_dialog.comboBox_label.setEditable(True)
        records = query_KMCfg_All(kmtype="1")
        for record in records:
            transfer_dialog.comboBox_label.addItem(record.name)

        # transfer_dialog.populate_combobox()
        form_layout.addRow("标签：", transfer_dialog.comboBox_label)


        # 创建单行文本编辑器和标签
        transfer_dialog.descEdit = QPlainTextEdit()
        form_layout.addRow("描述：", transfer_dialog.descEdit)

        # 将表单布局添加到主布局
        main_layout.addLayout(form_layout)

        # 创建水平布局用于按钮
        button_layout = QHBoxLayout()
        button_layout.addStretch(1)  # 添加弹性空间，使按钮靠右对齐

        ok_button = QPushButton("确定")
        cancel_button = QPushButton("取消")
        ok_button.clicked.connect(transfer_dialog.accept)
        cancel_button.clicked.connect(transfer_dialog.reject)

        # 将按钮添加到水平布局
        button_layout.addWidget(ok_button)
        button_layout.addWidget(cancel_button)

        # 将按钮布局添加到主布局
        main_layout.addLayout(button_layout)

        # 设置主布局
        transfer_dialog.setLayout(main_layout)

        if transfer_dialog.exec_():
            # 在对话框被接受时执行的代码
            title = transfer_dialog.titleEdit.text()
            selected_label = transfer_dialog.comboBox_label.currentText()
            desc = transfer_dialog.descEdit.toPlainText()
            self.work_flow_title= title
            self.work_flow_label= selected_label
            self.work_flow_desc= desc


            print(f"Selected desc: {desc}, selected_label: {selected_label}, Title: {title}")

        """
                        转换选定历史记录中的消息为工作流节点和连接器。
        """
        self.pre_system_role_prompt = self.system_role_prompt
        self.system_role_prompt = get_prompt_by_title("Workflow_Specialist")
        self.is_transfer_to_workflow = True
        message = "请处理"
        self.messageEdit.setPlainText(message)
        self.sendMessage()





    def explain_text(self, txt):
        self.messageEdit.setPlainText(f"给我解释一下以下内容：{txt}")
        self.sendMessage()


    def is_urlbak(self, text):
        url_regex = re.compile(
            r'^(?:'
            r'((https?|ftp)://)?'  # 可选的 http:// 或 https:// 或 ftp://
            r'(localhost|'  # localhost
            r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|'  # IPv4
            r'\[?[A-F0-9]*:[A-F0-9:]+\]?|'  # IPv6
            r'www\.'  # www.
            r'(?:[A-Z0-9](?:[A-Z0-9-]{0,61}[A-Z0-9])?\.)+'  # 主域名部分
            r'(?:[A-Z]{2,6}\.?|[A-Z0-9-]{2,}\.?)'  # 顶级域名
            r')'
            r'(?::\d+)?'  # 可选的端口
            r'(?:/?|[/?]\S*)'  # 路径
            r')\s*$', re.IGNORECASE)  # 末尾可能有空格
        return re.match(url_regex, text.strip()) is not None

    def is_url(self, text):
        """
        判断给定的文本是否为有效的URL地址，包括考虑localhost和IP地址形式。

        :param text: 需要检查的文本字符串
        :return: 如果文本是有效的URL则返回True，否则返回False
        """
        ip_pattern = re.compile(r'^(?:\d{1,3}\.){3}\d{1,3}$')
        try:
            result = urlparse(text)
            # 添加对没有明确协议但看起来像IP或localhost的处理
            if not all([result.scheme, result.netloc]):
                # 尝试在没有协议的情况下解析
                if ip_pattern.match(text.strip()) or text.strip() == 'localhost' or text.strip().startswith('www.'):
                    return True
            else:
                return all([result.scheme, result.netloc])
        except ValueError:
            return False



    def toggle_search_box(self):
        print("..taskpage searching..")
        if self.search_box.isVisible():
            self.search_box.setVisible(False)
            self.search_button.setVisible(False)
            self.messageBrowser.findText("")  # 清除搜索状态
            self.search_box.clear()  # 清空搜索框的内容
        else:
            self.search_box.setVisible(True)
            self.search_button.setVisible(True)
            self.search_box.setFocus()

    def search_in_page(self):
        search_text = self.search_box.text()
        self.messageBrowser.findText(search_text)



    def open_file(self, file_path):
        if sys.platform == "win32":
            os.startfile(file_path)
        elif sys.platform == "darwin":
            subprocess.call(("open", file_path))
        else:
            subprocess.call(("xdg-open", file_path))

    def add_attachment_area(self, attachments):
        self.remaining_attachments += len(attachments)
        self.current_attachment_list += attachments  # 更新附件列表

        if not hasattr(self, 'attachment_frame'):
            self.attachment_frame = QFrame()
            self.attachment_frame.setObjectName("attachmentFrame")
            self.attachment_layout = QHBoxLayout(self.attachment_frame)
            self.attachment_layout.setObjectName("attachmentLayout")
            self.attachment_layout.setContentsMargins(0, 0, 0, 0)
            self.attachment_layout.setAlignment(Qt.AlignCenter)
            self.attachment_frame.setMaximumHeight(40)
            self.vboxlayout.insertWidget(3, self.attachment_frame)

        self.attachment_frame.setVisible(True)

        for attachment in attachments:
            file_content_tuple = get_file_content_tuple(attachment)
            print(file_content_tuple)
            self.attachment_content_list.append(file_content_tuple)  # 将附件内容添加到列表
            # self.current_attachment_content += "\n" + file_content_tuple  # 更新合并的内容
            file_name = os.path.basename(attachment)
            attachment_label = QLabel(f'<a href="#">{file_name}</a>')
            attachment_label.setOpenExternalLinks(False)
            attachment_label.linkActivated.connect(lambda _, file=attachment: self.open_file(file))

            delete_label = QLabel('<a href="#" style="color:red">删除</a>')
            delete_label.setOpenExternalLinks(False)
            delete_label.linkActivated.connect(lambda _, lbl=attachment_label, del_lbl=delete_label, file=attachment: self.remove_attachment(lbl, del_lbl, file))

            self.attachment_layout.addWidget(attachment_label)
            self.attachment_layout.addWidget(delete_label)

            # 存储附件标签以便后续删除
            self.attachment_labels.append((attachment_label, delete_label))

            self.attachment_layout.setAlignment(QtCore.Qt.AlignCenter)

    def remove_attachment(self, attachment_label, delete_label, attachment):
        # 从附件列表中移除
        index = self.current_attachment_list.index(attachment)
        if index >= 0:
            self.current_attachment_list.pop(index)  # 从当前附件列表中删除
            self.attachment_content_list.pop(index)  # 从附件内容列表中删除

        # 更新 current_attachment_content
        # self.current_attachment_content = "\n".join(self.attachment_content_list)  # 重新组合内容

        # 隐藏标签
        attachment_label.setVisible(False)
        delete_label.setVisible(False)
        self.remaining_attachments -= 1
        self.check_attachments_visibility()

    def remove_all_attachments(self):
        """删除所有附件及其内容"""
        for attachment_label, delete_label in self.attachment_labels:
            attachment_label.setVisible(False)  # 隐藏附件标签
            delete_label.setVisible(False)  # 隐藏删除标签

        self.current_attachment_list.clear()  # 清空当前附件列表
        self.attachment_content_list.clear()  # 清空附件内容列表
        # self.current_attachment_content = ""  # 重置合并后的附件内容
        self.remaining_attachments = 0  # 更新剩余附件计数

        # 隐藏附件框
        if hasattr(self, 'attachment_frame'):
            self.attachment_frame.setVisible(False)

        # 清空附件标签列表
        self.attachment_labels.clear()

    def check_attachments_visibility(self):
        if self.remaining_attachments == 0:
            self.attachment_frame.setVisible(False)

    def toggle_page_all_checkboxes_status(self, state):
        """
        根据复选框的状态调用相应的JavaScript函数
        :param state: 当前复选框的状态，0为未选中，2为选中
        """
        if state == 2:  # 复选框被选中
            # 调用 JavaScript 函数将所有复选框设为选中
            self.messageBrowser.page().runJavaScript('setAllCheckboxesChecked(true);')
        else:  # 复选框未选中
            # 调用 JavaScript 函数将所有复选框设为未选中
            if self.conten_menu_closing == True:#点击了内容菜单的关闭按钮
                if self.history_mode_checkbox.isChecked()==False:#如果没有选中指定上下文
                    self.messageBrowser.page().runJavaScript('setAllCheckboxesChecked(false);')

                self.conten_menu_closing = False#处理好复原

            else:#如果不是点击关闭内容菜单按钮
                self.messageBrowser.page().runJavaScript('setAllCheckboxesChecked(false);')



class SearchBox(QLineEdit):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent = parent

    def keyPressEvent(self, event):
        if event.key() == Qt.Key_Escape:
            self.parent.toggle_search_box()
        else:
            super().keyPressEvent(event)
